### ISSUE TITLE
Multi-threaded MPI communication

### ISSUE THREAD

**Issue by mshiryaev** [lanl/SNAP#7]
Hello,

I wonder if multiple endpoints feature from Intel MPI 2019 can be beneficial for SNAP. As far as I understand SNAP has mode in which multiple OpenMP threads can communicate over MPI in parallel.

You can find more information about multiple endpoints here:
https://software.intel.com/en-us/mpi-developer-guide-linux-multiple-endpoints-support
https://software.intel.com/en-us/mpi-developer-guide-linux-examples

**Comment by zerr** [comment]
Will take a look. Thanks!

**Comment by mshiryaev** [comment]
@zerr thanks for reply. In case of questions feel free to contact me directly over email (mikhail.shiryaev@intel.com).

**Comment by zerr** [comment]
Still have this noted as question for investigation, but closing the ticket unless (until) further feedback is needed. Thanks.
