### ISSUE TITLE
Fails to compile with `MPI=no`

### ISSUE THREAD

**Issue by benbenolson** [lanl/SNAP#8]
On line 515 and 516 of `thrd_comm.f90`, a call to `tests` is made that includes one argument. However, if `-DMPI` is *not* specified, the `tests` function that gets defined in `plib.f90` has two arguments. The result is that, if the user sets `MPI = no` in the `Makefile`, SNAP fails to compile.

https://github.com/lanl/SNAP/blob/bb272390cc32671493c5b1cc500134161240f04a/src/thrd_comm.f90#L515

**Comment by zerr** [comment]
Brain fart. Fixed now. Thanks!
