### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by abeltre1** [lanl/SNAP#9]
I am trying to run your code and I am unable to get the right libraries in the makefile. 

[cc@kubeib-1 src]$ make
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c global.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c sn.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c data.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c geom.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c control.f90
cpp -P -DMPI -DOPENMP time.F90 >time.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c time.f90
cpp -P -DMPI -DOPENMP plib.F90 >plib.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c plib.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c mms.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c solvar.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c dealloc.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c utils.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c version.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c input.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c setup.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c output.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c snap_main.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c expxs.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c thrd_comm.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c dim1_sweep.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c dim3_sweep.f90
mpif90 -Ofast -funroll-loops -march=native -fopenmp -c mkba_sweep.f90
mkba_sweep.f90:161.8:

  !$OMP PARALLEL DO NUM_THREADS(nnstd_used) IF(nnstd_used>1)           &
        1
Error: Unclassifiable OpenMP directive at (1)
mkba_sweep.f90:446.23:

  !$OMP END PARALLEL DO
                       1
Error: Unexpected !$OMP END PARALLEL DO statement at (1)
make: *** [mkba_sweep.o] Error 1

**Comment by zerr** [comment]
Hi. I need some more detail. Which gcc/gfortran and OpenMP are you using? Where is that '1' character for the first error? I doubt it's actually under the '!'.

**Comment by abeltre1** [comment]
Hello @zerr, 

I was able to compile it the following way or by using the flag for the openMP 
`
OMPFLAG = -L/usr/lib/gcc/i686-linux-gnu/4.4/ -lgomp
`

But I get the following error when I execute, which seems to just be missing a particular file. 
  
`` ***ERROR: CMDARG: Missing command line entry``                    
``Aww SNAP. Program failed. Try again.``

can you show me an example execution command (e.g., mpirun -np XX ) ?

**Comment by zerr** [comment]
Good!

Basic: mpirun -n #ranks path_to/gsnap input_file_name output_file_name

More details in main Readme under "Usage," namely to consider which options you'll want for thread-binding.

Let me know if we can close this issue. Thanks.

**Comment by abeltre1** [comment]
I can't locate the right input files, do you have a basic one or where can I find it? @zerr

**Comment by zerr** [comment]
https://github.com/lanl/SNAP/tree/master/qasnap has many examples.
